### PR TITLE
Add jQuery 1.9 support

### PR DESCRIPTION
**Pull request by zessx**

### CODE REVIEW

**Comment by MarkTraceur** [comment]
@cowboy it would be super to get this merged - we're using it in a project that's moving to 1.9 and I'd love to knock out the hashchange upgrade in the same commit as the other 1.9 changes we're making.

Thanks!

**Comment by dharapvj** [comment]
+1

**Comment by williamdes** [comment]
Part of https://www.npmjs.com/package/jquery-hashchange/v/1.4.0

**Comment by williamdes** [comment]
Oh my gosh open for 8 years, cleanup day I assume

**Comment by zessx** [comment]
Ahem, I confess 😅

**Pull request closed without merging**
